=== cristianhoyos66-zz/PAIE/src/co/com/poli/aerolinea/aerolinea.dtd
<!ELEMENT aerolinea (viaje)+>
<!ELEMENT viaje (datosvuelo, datosavion)> 
<!ELEMENT datosvuelo (escalas, tiempoduracion)*> 
<!ELEMENT escalas (#PCDATA)*>
<!ELEMENT tiempoduracion (#PCDATA)>
<!ELEMENT datosavion (#PCDATA)>

<!ATTLIST viaje nombreempresa CDATA #REQUIRED
                feha CDATA #REQUIRED>

<!ATTLIST datosvuelo    nombretrayecto CDATA #REQUIRED
                        origen CDATA #REQUIRED
                        destino CDATA #REQUIRED>

<!ATTLIST escalas   ciudad CDATA #REQUIRED
                    hora CDATA #REQUIRED
                    id ID #REQUIRED>
                  
<!ATTLIST tiempoduracion    horasalida CDATA #REQUIRED
                            horallegada CDATA #REQUIRED
                            tiempototal CDATA #REQUIRED>

<!ATTLIST datosavion    referenciaavion CDATA #REQUIRED
                        nombrecapitan CDATA #REQUIRED
                        pasajeros CDATA #REQUIRED
                        observaciones CDATA #REQUIRED>

=== cristianhoyos66-zz/PAIE/src/co/com/poli/aerolinea/aerolinea.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aerolinea SYSTEM "aerolinea.dtd">
<aerolinea>
    <viaje nombreempresa="aerolineaA" fecha="20/16/2015">
        <datosvuelo nombretrayecto="trayectoprueba" origen="Medellin" destino="Bogota">
            <escala ciudad="California" hora="10:08pm" id="1">
                
            </escala>
        </datosvuelo>
        <datosavion referenciaavion="efd" nombrecapitan="Carlos" pasajeros="50" observaciones="">
            
        </datosavion>
    </viaje>
    
    <viaje nombreempresa="aerolineaA" fecha="20/16/2015">
        <datosvuelo nombretrayecto="trayectoprueba" origen="Medellin" destino="Bogota">
            <tiempoduracion horasalida="09:05pm" horallegada="10:08pm" tiempototal="1">
                
            </tiempoduracion>
        </datosvuelo>
        <datosavion referenciaavion="efd" nombrecapitan="Miguel" pasajeros="50" observaciones="">
            
        </datosavion>
    </viaje>

</aerolinea>
