=== cristianhoyos66-zz/PAIE/src/co/com/poli/ejemplo1schema/curso.xsd
<?xml version="1.0"?>

<xs:schema 
    version="1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">    
    <xs:element 
        name="cursos">        
        <xs:complexType>
            <xs:sequence>
                <xs:element 
                    name="modulo">
                    <xs:complexType mixed="true">
                        <xs:attribute 
                            name="codigo"
                            type="xs:string"
                            use="required">
                            
                        </xs:attribute>
                    </xs:complexType>                    
                </xs:element>
                <xs:element 
                    name="profesor"
                    type="xs:string">
                    
                </xs:element>
                <xs:element 
                    name="estudiantes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element 
                                name="estudiante"
                                minOccurs="0"
                                maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element 
                                            name="nombre" 
                                            type="xs:string">                                            
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute 
                                        name="codigo" 
                                        type="TipoCodigoEstudiante2"
                                        use="optional">                                        
                                    </xs:attribute>
                                    <xs:attribute 
                                        name="sexo" 
                                        type="tipoSexo"
                                        use="required">                                        
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element 
                    name="cantidadAlumnos" 
                    type="xs:double">                    
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
    
    <xs:simpleType 
        name="tipoSexo">
        <xs:restriction
            base="xs:string">
            <xs:enumeration 
                value="M">
            </xs:enumeration>
            <xs:enumeration 
                value="F">
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType
        name="TipoCodigoEstudiante">
        <xs:restriction
            base="xs:integer">
            <xs:totalDigits 
                value="10">
                
            </xs:totalDigits>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType
        name="TipoCodigoEstudiante2">
        <xs:restriction
            base="xs:string">
            <xs:pattern 
                value="[A-Z]{3}[-]{1}[0-9]{2}">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== cristianhoyos66-zz/PAIE/src/co/com/poli/ejemplo1schema/curso.xml
<?xml version="1.0" encoding="UTF-8"?>
<cursos 
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:noNamespaceSchemaLocation="curso.xsd">
    <modulo codigo="255-A">
        Java
    </modulo>
    <profesor>
        Jose
    </profesor>
    <estudiantes>
        <estudiante 
            codigo="10" 
            sexo="F">
            <nombre>
                Jorge
            </nombre>
        </estudiante>
        <estudiante
            sexo="F">
            <nombre>
                Anastacha
            </nombre>
        </estudiante>
        <estudiante 
            sexo="F" 
            codigo="A80">
            <nombre>
                Mascha
            </nombre>
        </estudiante>
    </estudiantes>
    <cantidadAlumnos>
        56
    </cantidadAlumnos>
</cursos>
